apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightctl-api
  labels:
    app: flightctl-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightctl-api
  template:
    metadata:
      labels:
        app: flightctl-api
    spec:
      containers:
        - name: flightctl-api
          image: 10.200.170.11:5000/flightctl/flightctl-api:v1.2.0-main-183-g8992db6d
          imagePullPolicy: Always
          ports:
            - containerPort: 3443
---
apiVersion: v1
kind: Service
metadata:
  name: flightctl-api
spec:
  selector:
    app: flightctl-api
  ports:
    - protocol: TCP
      port: 3443
      targetPort: 3443
