defaultNamespace: flightctl-dev
targetCustomizations:
  # --- DEV ENVIRONMENT ---
  - name: dev-environment
    namespace: flightctl-dev
    clusterSelector:
      matchLabels:
        fleet.cattle.io/cluster: local

  # --- QA ENVIRONMENT ---
  - name: qa-environment
    namespace: flightctl-qa
    clusterSelector:
      matchLabels:
        fleet.cattle.io/cluster: local
