# -- Global parameters
global:
  enableOpenShiftExtensions: "auto"
  enableMulticlusterExtensions: "auto"
  multiclusterEngineNamespace: "multicluster-engine"
  generateCertificates: "auto"
  internalNamespace: ""
  baseDomain: "flightctl.local"
  baseDomainTlsSecretName: ""
  storageClassName: ""
  imagePullSecretName: ""
  imagePullPolicy: Always
  auth:
    type: "k8s" 
    caCert: ""
    insecureSkipTlsVerify: false
    k8s:
      apiUrl: https://kubernetes.default.svc
      externalApiTokenSecretName: ""
      rbacNs: ""
      createAdminUser: true
    oidc:
      clientId: "flightctl-client"
      issuer: ""
      externalOidcAuthority: ""
      organizationAssignment:
        type: "static"
        organizationName: "default"
      usernameClaim:
        - "preferred_username"
      roleAssignment:
        type: "dynamic"
        claimPath:
          - "groups"
    aap:
      apiUrl: ""
      externalApiUrl: ""
    openshift:
      createAdminUser: true
      clusterControlPlaneUrl: "https://kubernetes.default.svc"
      externalApiTokenSecretName: ""
      clientId: ""
      clientSecret: ""
      authorizationUrl: ""
      tokenUrl: ""
      issuer: ""
      projectLabelFilter: ""
  exposeServicesMethod: "none"
  gateway:
    gatewayClassName: ""
    ports:
      tls: 443
      http: 80
  sshKnownHosts:
    data: ""
  additionalRouteLabels: null
  additionalPVCLabels: null

# -- Component specific parameters

# -- Database Configuration
db:
  type: "builtin"
  name: "flightctl"
  builtin:
    applicationUserSecretName: ""
    migrationUserSecretName: ""
    masterUserSecretName: ""
    image:
      image: 10.200.170.11:5000/postgresql-16-c9s
      tag: "20250214"
      pullPolicy: Always
    maxConnections: 200
    storage:
      size: "60Gi"
    resources:
      requests:
        cpu: "512m"
        memory: "512Mi" 
    fsGroup: ""
    additionalPVCLabels: null
  external:
    hostname: ""
    port: 5432
    applicationUserSecretName: ""
    migrationUserSecretName: ""
    sslmode: ""
    tlsConfigMapName: ""
    tlsSecretName: ""

# -- Key-Value Store Configuration
kv:
  image:
    image: 10.200.170.11:5000/redis-7-c9s
    tag: "20250108"
    pullPolicy: Always
  passwordSecretName: ""
  loglevel: warning
  fsGroup: ""
  maxmemory: "1gb"
  maxmemoryPolicy: "allkeys-lru"

# -- Alertmanager Configuration
alertmanager:
  enabled: true
  image:
    image: 10.200.170.11:5000/alertmanager
    tag: "v0.28.1"
    pullPolicy: Always
  additionalRouteLabels: null
  additionalPVCLabels: null

# -- API Server Configuration
api:
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-api
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  rateLimit:
    enabled: true
    requests: 300
    window: "1m"
    authRequests: 20
    authWindow: "1h"
    trustedProxies:
      - "10.0.0.0/8"   
      - "172.16.0.0/12" 
      - "192.168.0.0/16" 
  additionalRouteLabels: null
  additionalPVCLabels: null

# -- CLI Artifacts Configuration
cliArtifacts:
  enabled: true
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-cli-artifacts
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  additionalRouteLabels: null

# -- Worker Configuration
worker:
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-worker
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  clusterLevelSecretAccess: false

# -- Periodic Configuration
periodic:
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-periodic
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  consumers: 5

# -- Alert Exporter Configuration
alertExporter:
  enabled: true
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-alert-exporter
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always

# -- Alertmanager Proxy Configuration
alertmanagerProxy:
  enabled: true
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-alertmanager-proxy
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  
# -- ImageBuilder API Configuration
imageBuilderApi:
  enabled: true
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-imagebuilder-api
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always

# -- ImageBuilder Worker Configuration
imageBuilderWorker:
  enabled: true
  replicas: 1
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-imagebuilder-worker
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  logLevel: info
  maxConcurrentBuilds: 2
  defaultTTL: 168h
  privileged: true
  yumReposSecretName: ""
  rhsmSecretName: ""
  rhsmCaSecretName: ""
  resources: {}

telemetryGateway:
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-telemetry-gateway
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  additionalRouteLabels: null

# -- UI Configuration (Disabled)
ui:
  enabled: true
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-ui
    pluginImage: quay.io/flightctl/flightctl-ocp-ui
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  auth:
    insecureSkipTlsVerify: false
    caCert: ""
  additionalRouteLabels: null

# -- Cluster CLI Configuration
clusterCli:
  image:
    image: 10.200.170.11:5000/origin-cli
    tag: "4.20.0"
    pullPolicy: Always

# -- Database Setup Configuration
dbSetup:
  image:
    image: 10.200.170.11:5000/flightctl/flightctl-db-setup
    tag: "v1.2.0-main-184-g3aa428ca"
    pullPolicy: Always
  wait:
    timeout: 60
    sleep: 2
  migration:
    backoffLimit: 2147483647
    activeDeadlineSeconds: 0

# -- Upgrade hooks
upgradeHooks:
  scaleDown:
    condition: chart
    deployments:
      - flightctl-periodic
      - flightctl-worker
    timeoutSeconds: 120
  databaseMigrationDryRun: true
